[DEFAULT]
; Obtain from DataHub Endpoints UI
BASE_URL=https://spark-cluster-arm-gateway.pdf-jul2.a465-9q4k.cloudera.site/spark-cluster-arm/cdp-proxy/spark3history
; Obtain from Knox Token Management UI
KNOX_TOKEN=
PASS_TOKEN=False