[DEFAULT]
; Obtain from DataHub Endpoints UI
BASE_URL=https://ares-base-es01.ares.olympus.cloudera.com:8443/gateway/cdp-proxy/spark3history/
; Obtain from Knox Token Management UI
KNOX_TOKEN=
PASS_TOKEN=True